### ISSUE TITLE
research code to proceed the demo?

### ISSUE THREAD

**Issue by AnnaNAKAMURA7** [txipi/Labclock-Web#3]
Hello, 
first of all, I appreciate your excellent work. I was just struggling to build the clock on browsers...
One quick question is that a code is asked at the 'Get ready' page and I couldn't proceed to the experiment (or is the demo ended here?)
It will be very helpful to know the solution.
Thank you in advance, Anna.

**Comment by txipi** [comment]
Hi Anna,

the code is defined in experimentA.js and experimentB,js files of the demo and is 99 ;)

Best wishes,
Pablo

**Comment by AnnaNAKAMURA7** [comment]
Hello Pablo,
sorry that I missed it!
Thank you for your help,
Anna

**Comment by txipi** [comment]
Hi Anna,

the code is defined in experimentA.js and experimentB,js files of the demo and is 99 ;)

Best wishes,
Pablo
